<h3><?php echo $thread->getSubject(); ?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li><a href="<?php echo $this->url('edpforum', array(
      'tagslug' => $tag->getSlug(),
      'tagid' => $tag->getTagId()
  )); ?>"><?php echo $tag->getName(); ?></a></li>
  <li class="active"><?php echo $thread->getSubject(); ?></li>
</ol>

<?php foreach ($messages as $message): ?>
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h4 class="pull-left"><?php echo $message->getSubject(); ?></h4>
        <small class="text-muted pull-right"><?php echo date_format($message->getPostTime(), 'H:i D d M Y'); ?></small>
    </div>
    <div class="panel-body">
        <p><?php echo $message->getMessage(); ?></p>
    </div>
</div>
<?php endforeach; ?>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">New Message</h4>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->form;
            $form->prepare();
	        $form->setAttribute('action', $this->url('edpforum/thread', array(
	            'tagslug'    => $this->tag->getSlug(),
	            'tagid'      => $this->tag->getTagId(),
	            'threadslug' => $this->thread->getSlug(),
	            'threadid'   => $this->thread->getThreadId(),
	            'action'     => 'newmessage')));
	        $form->setAttribute('method', 'post');
	        echo $this->renderForm($form);	
        ?>
    </div>
</div>
    