<?php foreach ($messages as $message): ?>
<hr>
<div class="discuss-message">
    <div class="discuss-body">
        <small class="text-muted pull-right"><?php echo $this->dateFormat(
            $message->getPostTime(),
            IntlDateFormatter::MEDIUM, // date
            IntlDateFormatter::MEDIUM
        ); ?></small>
        <div class="discuss-heading">
            <h4><?php echo $message->getSubject(); ?></h4>
        </div>
        <?php echo $message->getMessage(); ?>
    </div>
</div>
<?php endforeach; ?>
