<h1><?php echo $this->translate('New Message'); ?></h1>

<?php
    $form = $this->form;
    $form->prepare();
	$form->setAttribute('action', $this->url('edpforum/thread', array(
	    'tagslug'    => $this->tag->getSlug(),
	    'tagid'      => $this->tag->getTagId(),
	    'threadslug' => $this->thread->getSlug(),
	    'threadid'   => $this->thread->getThreadId(),
	    'action'     => 'newmessage')));
	$form->setAttribute('method', 'post');
	echo $this->renderForm($form);	
?>
