<h4>New message</h4>
<?php
    $form = $this->form;
	$form->setAttribute('action', $this->url('edpforum/thread', array(
	    'tagslug'    => $this->tag->getSlug(),
	    'tagid'      => $this->tag->getTagId(),
	    'threadslug' => $this->thread->getSlug(),
	    'threadid'   => $this->thread->getThreadId(),
	    'action'     => 'addmessage')));
	$form->get('submit')->setAttribute('Value', 'Add');
	echo $this->RenderForm($form);
?>