<h3><?php echo $this->translate('New Thread'); ?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li><a href="<?php echo $this->url('edpforum', array(
      'tagslug' => $tag->getSlug(),
      'tagid' => $tag->getTagId()
  )); ?>"><?php echo $tag->getName(); ?></a></li>
  <li class="active">New Thread</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">New Thread</h4>
    </div>
    <div class="panel-body">
        <?php
        $form = $this->form;
        $form->prepare();
	    $form->setAttribute('action', $this->url('edpforum', array(
	        'tagslug'    => $this->tag->getSlug(),
	        'tagid'      => $this->tag->getTagId(),
	        'action'     => 'newthread')));
	    $form->setAttribute('method', 'post');
	    echo $this->renderForm($form);	
        ?>
    </div>
</div>
