<h3><?php echo $tag->getName()?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li class="active"><?php echo $tag->getName(); ?></li>
</ol>

<table class="table table-hover">

    <thead>
    <tr>
        <th>Threads</th>
        <th>Views</th>
        <th>Posts</th>
        <th>Last Post</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($threads as $thread): ?>
    <tr>
        <td>
            <a href="<?php echo $this->url('edpforum/thread', array(
                'tagslug' => $tag->getSlug(),
                'tagid' => $tag->getTagId(),
                'threadslug' => $thread->getSlug(),
                'threadid' => $thread->getThreadId()
            )); ?>"><?php echo $thread->getSubject(); ?></a>
        </td>
        <td>
            <span>:todo placeholder</span>
        </td>
        <td>
            <span>:todo placeholder</span>
        </td>
        <td>
            <span>:todo placeholder</span>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    
</table>
