<h3><?php echo $tag->getName()?></h3>

<ol class="breadcrumb">
  <li><a href="<?php echo $this->url('forum'); ?>">Forum List</a></li>
  <li class="active"><?php echo $tag->getName(); ?></li>
</ol>

<table class="table table-hover">

    <thead>
    <tr>
        <th>Threads</th>
        <th>Views</th>
        <th>Posts</th>
        <th>Last Post</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($threads as $thread): ?>
    <tr>
        <td>
            <a href="<?php echo $this->url('edpforum/thread', array(
                'tagslug' => $tag->getSlug(),
                'tagid' => $tag->getTagId(),
                'threadslug' => $thread->getSlug(),
                'threadid' => $thread->getThreadId()
            )); ?>"><?php echo $thread->getSubject(); ?></a>
        </td>
        <td>
            <span><?php echo $thread->getVisitCount(); ?></span>
        </td>
        <td>
            <span><?php echo $thread->getMessageCount(); ?></span>
        </td>
        <td>
            <span><?php echo $thread->getLastPost(); ?></span>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
    
</table>

<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        <h4 class="pull-left">New Thread</h4>
    </div>
    <div class="panel-body">
        <?php
            $form = $this->form;
            $form->prepare();
	        $form->setAttribute('action', $this->url('edpforum/newthread', array(
	            'tagslug'    => $this->tag->getSlug(),
	            'tagid'      => $this->tag->getTagId(),
	        )));
	        $form->setAttribute('method', 'post');
	        echo $this->renderForm($form);	
        ?>
    </div>
</div>
